from __future__ import annotations

import json
import subprocess
from pathlib import Path
from types import SimpleNamespace

import dotman.cli as cli
import pytest
from dotman.cli import PendingSelectionItem, main, prompt_for_excluded_items
from dotman.models import Binding, BindingPlan, DirectoryPlanItem, HookPlan, TargetPlan

from test_support import (
    EXAMPLE_REPO,
    REFERENCE_REPO,
    capture_parser_help,
    write_implicit_conflict_repo,
    write_manager_config,
    write_multi_instance_repo,
    write_named_manager_config,
    write_package_override_preview_repo,
    write_profile_switch_repo,
    write_untrack_conflict_repo,
)


def test_reconcile_editor_subcommand_invokes_editor_with_repo_live_and_additional_sources(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    include_path = tmp_path / "include-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")
    include_path.write_text("include\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        review_path = Path(command[1])
        assert review_path.name == "reconcile-review.md"
        assert review_path.read_text(encoding="utf-8") == "\n".join(
            [
                "# Dotman Reconcile Review",
                "",
                "Review only. Do not edit this file.",
                "Inspect the diff below, then edit the real repo source files listed under editable sources.",
                "",
                "## Review Inputs",
                "",
                f"- review repo path: {repo_path.resolve()}",
                f"- review live path: {live_path.resolve()}",
                "",
                "## Editable Sources",
                "",
                f"- {repo_path.resolve()}",
                f"- {include_path.resolve()}",
                "",
                "## Diff",
                "",
                "```diff",
                f"--- {repo_path.resolve()}",
                f"+++ {live_path.resolve()}",
                "@@ -1 +1 @@",
                "-repo",
                "+live",
                "```",
                "",
            ]
        )
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)

    exit_code = main(
        [
            "reconcile",
            "editor",
            "--editor",
            "nvim",
            "--repo-path",
            str(repo_path),
            "--live-path",
            str(live_path),
            "--additional-source",
            str(include_path),
        ]
    )

    assert exit_code == 0
    assert recorded["check"] is False
    command = recorded["command"]
    assert command[0] == "nvim"
    assert command[2:] == [
        str(repo_path.resolve()),
        str(include_path.resolve()),
    ]

def test_reconcile_editor_subcommand_fails_for_missing_additional_source(
    tmp_path: Path,
    capsys,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")

    exit_code = main(
        [
            "reconcile",
            "editor",
            "--editor",
            "true",
            "--repo-path",
            str(repo_path),
            "--live-path",
            str(live_path),
            "--additional-source",
            str(tmp_path / "missing-source"),
        ]
    )

    assert exit_code == 2
    assert "additional source does not exist" in capsys.readouterr().err
