from __future__ import annotations

import json
import subprocess
from pathlib import Path
from types import SimpleNamespace

import dotman.cli as cli
import dotman.reconcile as reconcile_module
import pytest
from dotman.cli import PendingSelectionItem, main, prompt_for_excluded_items
from dotman.models import FullSpecSelector, DirectoryPlanItem, HookPlan, TargetPlan

from tests.helpers import (
    EXAMPLE_REPO,
    REFERENCE_REPO,
    capture_parser_help,
    write_implicit_conflict_repo,
    write_manager_config,
    write_multi_instance_repo,
    write_named_manager_config,
    write_package_override_preview_repo,
    write_profile_switch_repo,
    write_untrack_conflict_repo,
)


def test_reconcile_editor_subcommand_invokes_editor_with_transactional_source_copies(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    include_path = tmp_path / "include-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")
    include_path.write_text("include\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        review_path = Path(command[1])
        editable_repo_path = Path(command[2])
        editable_include_path = Path(command[3])
        assert review_path.name == "reconcile-review.md"
        assert review_path.read_text(encoding="utf-8") == "\n".join(
            [
                "# Dotman Reconcile Review",
                "",
                "Review only. Do not edit this file.",
                "Inspect the diff below, then edit the temporary source copies listed under editable sources.",
                "Nothing is written back to the repo until dotman asks for confirmation after the editor exits.",
                "",
                "## Review Inputs",
                "",
                f"- review repo path: {repo_path.resolve()}",
                f"- review live path: {live_path.resolve()}",
                "",
                "## Editable Sources",
                "",
                f"- repo destination: {repo_path.resolve()}",
                f"  editable copy: {editable_repo_path}",
                f"- repo destination: {include_path.resolve()}",
                f"  editable copy: {editable_include_path}",
                "",
                "## Diff",
                "",
                "```diff",
                f"--- {repo_path.resolve()}",
                f"+++ {live_path.resolve()}",
                "@@ -1 +1 @@",
                "-repo",
                "+live",
                "```",
                "",
            ]
        )
        editable_repo_path.write_text("edited repo\n", encoding="utf-8")
        editable_include_path.write_text("edited include\n", encoding="utf-8")
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)
    monkeypatch.setattr(reconcile_module, "prompt", lambda _message: "y")

    exit_code = main(
        [
            "reconcile",
            "editor",
            "--editor",
            "nvim",
            "--repo-path",
            str(repo_path),
            "--live-path",
            str(live_path),
            "--additional-source",
            str(include_path),
        ]
    )

    assert exit_code == 0
    assert recorded["check"] is False
    command = recorded["command"]
    assert command[0] == "nvim"
    assert Path(command[2]) != repo_path.resolve()
    assert Path(command[3]) != include_path.resolve()
    assert repo_path.read_text(encoding="utf-8") == "edited repo\n"
    assert include_path.read_text(encoding="utf-8") == "edited include\n"

def test_reconcile_editor_subcommand_fails_for_missing_additional_source(
    tmp_path: Path,
    capsys,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")

    exit_code = main(
        [
            "reconcile",
            "editor",
            "--editor",
            "true",
            "--repo-path",
            str(repo_path),
            "--live-path",
            str(live_path),
            "--additional-source",
            str(tmp_path / "missing-source"),
        ]
    )

    assert exit_code == 2
    assert "additional source does not exist" in capsys.readouterr().err
