from __future__ import annotations

import difflib
import os
import shlex
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from dotman.terminal import preserve_terminal_state


ANSI_RESET = "\033[0m"
MENU_HEADER_MARKER = "::"
MENU_HEADER_MARKER_STYLE = ("1", "34")
MENU_PROMPT_STYLE = ("1",)
MENU_HINT_STYLE = ("2",)


@dataclass(frozen=True)
class EditableSourceCopy:
    destination_path: Path
    editable_copy_path: Path
    original_text: str


def prompt(message: str) -> str:
    sys.stdout.write(message)
    sys.stdout.flush()
    answer = sys.stdin.readline()
    return answer.strip()


def colors_enabled() -> bool:
    return sys.stdout.isatty() and os.environ.get("NO_COLOR") is None


def style_text(text: str, *codes: str) -> str:
    if not codes:
        return text
    return f"\033[{';'.join(codes)}m{text}{ANSI_RESET}"


def _resolve_editor_command(editor: str | None) -> list[str]:
    editor_value = editor or os.environ.get("VISUAL") or os.environ.get("EDITOR")
    if not editor_value:
        raise ValueError("reconcile editor requires --editor or $VISUAL/$EDITOR")
    return shlex.split(editor_value)


def _normalize_editor_command(editor_command: list[str]) -> list[str]:
    return [argument for argument in editor_command if argument != "-d"]


def _resolve_existing_path(path_value: str, *, label: str) -> Path:
    resolved = Path(path_value).expanduser().resolve()
    if not resolved.exists():
        raise ValueError(f"{label} does not exist: {resolved}")
    return resolved


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _read_diff_text(path: Path) -> list[str]:
    return _read_text(path).splitlines()


def _dedupe_paths(paths: list[Path]) -> list[Path]:
    ordered_paths: list[Path] = []
    for path in paths:
        if path not in ordered_paths:
            ordered_paths.append(path)
    return ordered_paths


def _build_review_content(
    *,
    repo_path: Path,
    live_path: Path,
    editable_sources: list[EditableSourceCopy],
) -> str:
    diff_lines = list(
        difflib.unified_diff(
            _read_diff_text(repo_path),
            _read_diff_text(live_path),
            fromfile=str(repo_path),
            tofile=str(live_path),
            lineterm="",
        )
    )
    if not diff_lines:
        diff_body = "No differences detected.\n"
    else:
        diff_body = "\n".join(diff_lines) + "\n"
    editable_sources_text = "\n".join(
        (
            f"- repo destination: {editable_source.destination_path}\n"
            f"  editable copy: {editable_source.editable_copy_path}"
        )
        for editable_source in editable_sources
    )
    return (
        "# Dotman Reconcile Review\n\n"
        "Review only. Do not edit this file.\n"
        "Inspect the diff below, then edit the temporary source copies listed under editable sources.\n"
        "Nothing is written back to the repo until dotman asks for confirmation after the editor exits.\n"
        "\n"
        "## Review Inputs\n\n"
        f"- review repo path: {repo_path}\n"
        f"- review live path: {live_path}\n\n"
        "## Editable Sources\n\n"
        f"{editable_sources_text}\n\n"
        "## Diff\n\n"
        "```diff\n"
        f"{diff_body}"
        "```\n"
    )


def _write_review_file(
    *,
    root: Path,
    repo_path: Path,
    live_path: Path,
    editable_sources: list[EditableSourceCopy],
) -> Path:
    review_path = root / "reconcile-review.md"
    review_path.write_text(
        _build_review_content(
            repo_path=repo_path,
            live_path=live_path,
            editable_sources=editable_sources,
        ),
        encoding="utf-8",
    )
    review_path.chmod(0o444)
    return review_path


def _write_editable_source_copies(*, root: Path, source_paths: list[Path]) -> list[EditableSourceCopy]:
    editable_sources: list[EditableSourceCopy] = []
    for index, source_path in enumerate(source_paths, start=1):
        editable_copy_path = root / f"editable-{index}-{source_path.name}"
        original_text = _read_text(source_path)
        editable_copy_path.write_text(original_text, encoding="utf-8")
        editable_sources.append(
            EditableSourceCopy(
                destination_path=source_path,
                editable_copy_path=editable_copy_path,
                original_text=original_text,
            )
        )
    return editable_sources


def _changed_editable_sources(editable_sources: list[EditableSourceCopy]) -> list[EditableSourceCopy]:
    return [
        editable_source
        for editable_source in editable_sources
        if _read_text(editable_source.editable_copy_path) != editable_source.original_text
    ]


def _reconcile_write_confirmation_prompt() -> str:
    prompt_text = "Write these changes?"
    hint_text = "[y/N]"
    if not colors_enabled():
        return f"{prompt_text} {hint_text} "
    # Keep reconcile prompt styling aligned with CLI confirmation prompts without
    # importing dotman.cli and creating a circular dependency.
    return (
        f"{style_text(MENU_HEADER_MARKER, *MENU_HEADER_MARKER_STYLE)} "
        f"{style_text(prompt_text, *MENU_PROMPT_STYLE)} "
        f"{style_text(hint_text, *MENU_HINT_STYLE)} "
    )


def _confirm_reconcile_write(*, changed_sources: list[EditableSourceCopy], assume_yes: bool = False) -> bool:
    print("Reconciled repo source changes:")
    for changed_source in changed_sources:
        print(f"  - {changed_source.destination_path}")
    if assume_yes:
        return True
    while True:
        answer = prompt(_reconcile_write_confirmation_prompt()).strip().lower()
        if answer in {"", "n", "no"}:
            return False
        if answer in {"y", "yes"}:
            return True
        print("invalid confirmation: enter 'y' or 'n'", file=sys.stderr)


def _write_confirmed_sources(changed_sources: list[EditableSourceCopy]) -> None:
    for changed_source in changed_sources:
        changed_source.destination_path.write_text(
            _read_text(changed_source.editable_copy_path),
            encoding="utf-8",
        )


def run_basic_reconcile(
    *,
    repo_path: str,
    live_path: str,
    additional_sources: list[str],
    review_repo_path: str | None = None,
    review_live_path: str | None = None,
    editor: str | None = None,
    assume_yes: bool = False,
) -> int:
    resolved_repo_path = _resolve_existing_path(repo_path, label="repo path")
    resolved_live_path = _resolve_existing_path(live_path, label="live path")
    resolved_review_repo_path = (
        _resolve_existing_path(review_repo_path, label="review repo path")
        if review_repo_path is not None
        else resolved_repo_path
    )
    resolved_review_live_path = (
        _resolve_existing_path(review_live_path, label="review live path")
        if review_live_path is not None
        else resolved_live_path
    )
    resolved_additional_sources = [
        _resolve_existing_path(path_value, label="additional source")
        for path_value in additional_sources
    ]

    editor_command = _normalize_editor_command(_resolve_editor_command(editor))
    source_paths = _dedupe_paths([resolved_repo_path, *resolved_additional_sources])
    with tempfile.TemporaryDirectory(prefix="dotman-reconcile-") as temp_dir:
        temp_root = Path(temp_dir)
        editable_sources = _write_editable_source_copies(root=temp_root, source_paths=source_paths)
        review_file_path = _write_review_file(
            root=temp_root,
            repo_path=resolved_review_repo_path,
            live_path=resolved_review_live_path,
            editable_sources=editable_sources,
        )
        with preserve_terminal_state():
            completed = subprocess.run(
                [
                    *editor_command,
                    str(review_file_path),
                    *(str(editable_source.editable_copy_path) for editable_source in editable_sources),
                ],
                check=False,
            )
        if completed.returncode != 0:
            return completed.returncode

        changed_sources = _changed_editable_sources(editable_sources)
        if not changed_sources:
            print("No reconciled repo source changes.")
            return 0
        if not _confirm_reconcile_write(changed_sources=changed_sources, assume_yes=assume_yes):
            return 0
        _write_confirmed_sources(changed_sources)
        return 0
