from __future__ import annotations

import difflib
import os
import shlex
import subprocess
import tempfile
from pathlib import Path


def _resolve_editor_command(editor: str | None) -> list[str]:
    editor_value = editor or os.environ.get("VISUAL") or os.environ.get("EDITOR")
    if not editor_value:
        raise ValueError("reconcile editor requires --editor or $VISUAL/$EDITOR")
    return shlex.split(editor_value)


def _normalize_editor_command(editor_command: list[str]) -> list[str]:
    return [argument for argument in editor_command if argument != "-d"]


def _resolve_existing_path(path_value: str, *, label: str) -> Path:
    resolved = Path(path_value).expanduser().resolve()
    if not resolved.exists():
        raise ValueError(f"{label} does not exist: {resolved}")
    return resolved


def _read_diff_text(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8", errors="replace").splitlines()


def _build_review_content(*, repo_path: Path, live_path: Path, editable_sources: list[Path]) -> str:
    diff_lines = list(
        difflib.unified_diff(
            _read_diff_text(repo_path),
            _read_diff_text(live_path),
            fromfile=str(repo_path),
            tofile=str(live_path),
            lineterm="",
        )
    )
    if not diff_lines:
        diff_body = "No differences detected.\n"
    else:
        diff_body = "\n".join(diff_lines) + "\n"
    editable_sources_text = "\n".join(f"- {path}" for path in editable_sources)
    return (
        "# Dotman Reconcile Review\n\n"
        "Review only. Do not edit this file.\n"
        "Inspect the diff below, then edit the real repo source files listed under editable sources.\n"
        "\n"
        "## Review Inputs\n\n"
        f"- review repo path: {repo_path}\n"
        f"- review live path: {live_path}\n\n"
        "## Editable Sources\n\n"
        f"{editable_sources_text}\n\n"
        "## Diff\n\n"
        "```diff\n"
        f"{diff_body}"
        "```\n"
    )


def _write_review_file(*, root: Path, repo_path: Path, live_path: Path, editable_sources: list[Path]) -> Path:
    review_path = root / "reconcile-review.md"
    review_path.write_text(
        _build_review_content(
            repo_path=repo_path,
            live_path=live_path,
            editable_sources=editable_sources,
        ),
        encoding="utf-8",
    )
    review_path.chmod(0o444)
    return review_path


def run_basic_reconcile(
    *,
    repo_path: str,
    live_path: str,
    additional_sources: list[str],
    review_repo_path: str | None = None,
    review_live_path: str | None = None,
    editor: str | None = None,
) -> int:
    resolved_repo_path = _resolve_existing_path(repo_path, label="repo path")
    resolved_live_path = _resolve_existing_path(live_path, label="live path")
    resolved_review_repo_path = (
        _resolve_existing_path(review_repo_path, label="review repo path")
        if review_repo_path is not None
        else resolved_repo_path
    )
    resolved_review_live_path = (
        _resolve_existing_path(review_live_path, label="review live path")
        if review_live_path is not None
        else resolved_live_path
    )
    resolved_additional_sources = [
        _resolve_existing_path(path_value, label="additional source")
        for path_value in additional_sources
    ]

    editor_command = _normalize_editor_command(_resolve_editor_command(editor))
    with tempfile.TemporaryDirectory(prefix="dotman-reconcile-") as temp_dir:
        temp_root = Path(temp_dir)
        review_file_path = _write_review_file(
            root=temp_root,
            repo_path=resolved_review_repo_path,
            live_path=resolved_review_live_path,
            editable_sources=[resolved_repo_path, *resolved_additional_sources],
        )
        ordered_paths: list[Path] = []
        for candidate_path in [review_file_path, resolved_repo_path, *resolved_additional_sources]:
            if candidate_path not in ordered_paths:
                ordered_paths.append(candidate_path)

        completed = subprocess.run(
            [*editor_command, *(str(path) for path in ordered_paths)],
            check=False,
        )
        return completed.returncode
