from __future__ import annotations

import difflib
import os
import shlex
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from dotman.atomic_files import write_text_atomic
from dotman.models import AdditionalSource, EditorSpec
from dotman.command_runtime import ArgvCommand, CommandRequest, CommandResult, ShellCommand, current_command_runtime
from dotman.file_access import read_bytes, write_bytes_atomic as sudo_write_bytes_atomic
from dotman.terminal import read_prompt_line


ANSI_RESET = "\033[0m"
MENU_HEADER_MARKER = "::"
MENU_HEADER_MARKER_STYLE = ("1", "34")
MENU_PROMPT_STYLE = ("1",)
MENU_HINT_STYLE = ("2",)


@dataclass(frozen=True)
class EditableSourceCopy:
    destination_path: Path
    editable_copy_path: Path
    original_text: str
    original_bytes: bytes = b""


def prompt(message: str) -> str:
    return read_prompt_line(message, input_stream=sys.stdin, output_stream=sys.stdout)


def colors_enabled() -> bool:
    return sys.stdout.isatty() and os.environ.get("NO_COLOR") is None


def style_text(text: str, *codes: str) -> str:
    if not codes:
        return text
    return f"\033[{';'.join(codes)}m{text}{ANSI_RESET}"


def _resolve_editor_value(editor: str | None) -> str:
    if editor:
        return editor
    for variable in ("VISUAL", "EDITOR", "GIT_EDITOR"):
        value = os.environ.get(variable)
        if value:
            return value

    # Ask Git for its effective editor so core.editor and Git's environment
    # precedence are handled in one place. Process execution stays behind the
    # command runtime seam, which is also used by engine and CLI callers.
    try:
        result = current_command_runtime().run(
            CommandRequest(
                command=ArgvCommand(("git", "config", "--get", "core.editor")),
                io="pipe",
                elevation="none",
            )
        )
    except (OSError, ValueError):
        result = None
    if result is not None and result.exit_code == 0:
        value = result.stdout_text.strip()
        if value:
            return value

    for candidate in ("sensible-editor", "editor", "nvim", "vim", "vi", "nano"):
        if shutil.which(candidate) is not None:
            return candidate
    raise ValueError("could not resolve an editor")


def _resolve_editor_command(editor: str | None) -> list[str]:
    return shlex.split(_resolve_editor_value(editor))


def _normalize_editor_command(editor_command: list[str]) -> list[str]:
    return [argument for argument in editor_command if argument != "-d"]


def _resolve_existing_path(path_value: str, *, label: str) -> Path:
    resolved = Path(path_value).expanduser().resolve()
    if not resolved.exists():
        raise ValueError(f"{label} does not exist: {resolved}")
    return resolved


def _read_text(path: Path, *, sudo_aware: bool = False) -> str:
    if sudo_aware:
        return read_bytes(path).decode("utf-8", errors="replace")
    return path.read_text(encoding="utf-8", errors="replace")


def _read_diff_text(path: Path, *, sudo_aware: bool = False) -> list[str]:
    return _read_text(path, sudo_aware=sudo_aware).splitlines()


def _dedupe_paths(paths: list[Path]) -> list[Path]:
    ordered_paths: list[Path] = []
    for path in paths:
        if path not in ordered_paths:
            ordered_paths.append(path)
    return ordered_paths


def _build_review_content(
    *,
    repo_path: Path,
    live_path: Path,
    editable_sources: list[EditableSourceCopy],
    live_path_sudo_aware: bool = False,
) -> str:
    diff_lines = list(
        difflib.unified_diff(
            _read_diff_text(repo_path),
            _read_diff_text(live_path, sudo_aware=live_path_sudo_aware),
            fromfile=str(repo_path),
            tofile=str(live_path),
            lineterm="",
        )
    )
    if not diff_lines:
        diff_body = "No differences detected.\n"
    else:
        diff_body = "\n".join(diff_lines) + "\n"
    editable_sources_text = "\n".join(
        (
            f"- repo destination: {editable_source.destination_path}\n"
            f"  editable copy: {editable_source.editable_copy_path}"
        )
        for editable_source in editable_sources
    )
    return (
        "# Dotman Reconcile Review\n\n"
        "Review only. Do not edit this file.\n"
        "Inspect the diff below, then edit the temporary source copies listed under editable sources.\n"
        "Nothing is written back to the repo until dotman asks for confirmation after the editor exits.\n"
        "\n"
        "## Review Inputs\n\n"
        f"- review repo path: {repo_path}\n"
        f"- review live path: {live_path}\n\n"
        "## Editable Sources\n\n"
        f"{editable_sources_text}\n\n"
        "## Diff\n\n"
        "```diff\n"
        f"{diff_body}"
        "```\n"
    )


def _write_review_file(
    *,
    root: Path,
    repo_path: Path,
    live_path: Path,
    editable_sources: list[EditableSourceCopy],
    live_path_sudo_aware: bool = False,
) -> Path:
    review_path = root / "reconcile-review.md"
    review_path.write_text(
        _build_review_content(
            repo_path=repo_path,
            live_path=live_path,
            editable_sources=editable_sources,
            live_path_sudo_aware=live_path_sudo_aware,
        ),
        encoding="utf-8",
    )
    review_path.chmod(0o444)
    return review_path


def _write_editable_source_copies(
    *, root: Path, source_paths: list[Path], source_bytes: Mapping[Path, bytes] | None = None,
) -> list[EditableSourceCopy]:
    editable_sources: list[EditableSourceCopy] = []
    for index, source_path in enumerate(source_paths, start=1):
        editable_copy_path = root / f"editable-{index}-{source_path.name}"
        original_bytes = source_bytes[source_path] if source_bytes is not None and source_path in source_bytes else read_bytes(source_path)
        original_text = original_bytes.decode("utf-8", errors="replace")
        editable_copy_path.write_bytes(original_bytes)
        editable_sources.append(
            EditableSourceCopy(
                destination_path=source_path,
                editable_copy_path=editable_copy_path,
                original_text=original_text,
                original_bytes=original_bytes,
            )
        )
    return editable_sources


def _changed_editable_sources(editable_sources: list[EditableSourceCopy]) -> list[EditableSourceCopy]:
    return [
        editable_source
        for editable_source in editable_sources
        if editable_source.editable_copy_path.read_bytes() != editable_source.original_bytes
    ]


def _reconcile_write_confirmation_prompt() -> str:
    prompt_text = "Write these changes?"
    hint_text = "[y/n]"
    if not colors_enabled():
        return f"{prompt_text} {hint_text} "
    # Keep reconcile prompt styling aligned with CLI confirmation prompts without
    # importing dotman.cli and creating a circular dependency.
    return (
        f"{style_text(MENU_HEADER_MARKER, *MENU_HEADER_MARKER_STYLE)} "
        f"{style_text(prompt_text, *MENU_PROMPT_STYLE)} "
        f"{style_text(hint_text, *MENU_HINT_STYLE)} "
    )


def _confirm_reconcile_write(*, changed_sources: list[EditableSourceCopy], assume_yes: bool = False) -> bool:
    print("Reconciled repo source changes:")
    for changed_source in changed_sources:
        print(f"  - {changed_source.destination_path}")
    if assume_yes:
        return True
    while True:
        answer = prompt(_reconcile_write_confirmation_prompt()).strip().lower()
        if answer in {"n", "no"}:
            return False
        if answer in {"y", "yes"}:
            return True
        print("invalid confirmation: enter 'y' or 'n'", file=sys.stderr)


def _write_confirmed_sources(changed_sources: list[EditableSourceCopy]) -> None:
    for changed_source in changed_sources:
        content = changed_source.editable_copy_path.read_bytes()
        try:
            write_text_atomic(
                changed_source.destination_path,
                content.decode("utf-8"),
            )
        except (PermissionError, UnicodeDecodeError):
            # Source inputs may be readable only through the elevation broker,
            # and binary editor inputs must still be copied byte-for-byte.
            sudo_write_bytes_atomic(changed_source.destination_path, content)


def resolve_editor_additional_sources(
    *,
    editor: EditorSpec | None,
    additional_sources: tuple[str, ...],
    additional_source_entries: tuple[AdditionalSource, ...],
    additional_sources_root: Path | None,
    package_root: Path,
) -> list[Path]:
    # Resolve each configured entry against the package that declared it.
    # Entries from inherited specs retain their parent root; appended entries
    # carry the child root. Manual plans without provenance use package_root.
    entries = list(additional_source_entries)
    if not entries:
        entries = list(editor.source_entries() if editor is not None else ())
    if not entries:
        fallback_root = additional_sources_root or package_root
        entries = [AdditionalSource(path, fallback_root) for path in additional_sources]
    elif additional_sources and len(entries) < len(additional_sources):
        known = {entry.path for entry in entries}
        entries.extend(AdditionalSource(path, additional_sources_root or package_root) for path in additional_sources if path not in known)

    source_paths: list[Path] = []
    for entry in entries:
        root = (entry.root or package_root).expanduser().resolve()
        source_path = (root / entry.path).resolve()
        try:
            source_path.relative_to(root)
        except ValueError as exc:
            raise ValueError(f"editor additional source escapes declaring package root: {entry.path}") from exc
        source_paths.append(source_path)
    return source_paths


def run_basic_reconcile(
    *,
    repo_path: str,
    live_path: str,
    additional_sources: list[str],
    review_repo_path: str | None = None,
    review_live_path: str | None = None,
    editor: str | None = None,
    assume_yes: bool = False,
    source_bytes: Mapping[Path, bytes] | None = None,
    review_repo_bytes: bytes | None = None,
    review_live_bytes: bytes | None = None,
    editor_env: Mapping[str, str] | None = None,
    editor_cwd: Path | None = None,
    editor_io: str = "tty",
    editor_elevation: str = "none",
    stream_output: bool = False,
    return_result: bool = False,
) -> int | CommandResult:
    resolved_repo_path = Path(repo_path).expanduser().resolve()
    if not resolved_repo_path.exists() and (
        source_bytes is None or resolved_repo_path not in source_bytes
    ):
        raise ValueError(f"repo path does not exist: {resolved_repo_path}")
    resolved_live_path = Path(live_path).expanduser().resolve()
    if not resolved_live_path.exists() and review_live_bytes is None:
        raise ValueError(f"live path does not exist: {resolved_live_path}")
    resolved_review_repo_path = (
        _resolve_existing_path(review_repo_path, label="review repo path")
        if review_repo_path is not None
        else resolved_repo_path
    )
    resolved_review_live_path = (
        _resolve_existing_path(review_live_path, label="review live path")
        if review_live_path is not None
        else resolved_live_path
    )
    resolved_additional_sources = [
        _resolve_existing_path(path_value, label="additional source")
        for path_value in additional_sources
    ]

    editor_value = _resolve_editor_value(editor)
    editor_command = _normalize_editor_command(shlex.split(editor_value))
    source_paths = _dedupe_paths([resolved_repo_path, *resolved_additional_sources])
    with tempfile.TemporaryDirectory(prefix="dotman-reconcile-") as temp_dir:
        temp_root = Path(temp_dir)
        editable_sources = _write_editable_source_copies(
            root=temp_root, source_paths=source_paths, source_bytes=source_bytes,
        )
        if review_repo_bytes is not None:
            resolved_review_repo_path = temp_root / "review-repo"
            resolved_review_repo_path.write_bytes(review_repo_bytes)
            resolved_review_repo_path.chmod(0o444)
        if review_live_bytes is not None:
            resolved_review_live_path = temp_root / "review-live"
            resolved_review_live_path.write_bytes(review_live_bytes)
            resolved_review_live_path.chmod(0o444)
        review_file_path = _write_review_file(
            root=temp_root,
            repo_path=resolved_review_repo_path,
            live_path=resolved_review_live_path,
            editable_sources=editable_sources,
            live_path_sudo_aware=resolved_review_live_path == resolved_live_path,
        )
        command_env = dict(editor_env or {})
        command_env.update({
            "DOTMAN_EDITOR_REVIEW_PATH": str(review_file_path),
            "DOTMAN_EDITOR_SOURCE_PATH": str(editable_sources[0].editable_copy_path),
            "DOTMAN_EDITOR_PRIMARY_PATH": str(editable_sources[0].editable_copy_path),
            "DOTMAN_EDITOR_TRANSACTIONAL_ROOT": str(temp_root),
            "DOTMAN_EDITOR_ADDITIONAL_SOURCE_PATHS": os.pathsep.join(
                str(source.editable_copy_path) for source in editable_sources[1:]
            ),
            # Existing command helpers use these names; point them at the
            # staged, readable inputs so an editor cannot mutate managed files.
            "DOTMAN_REVIEW_REPO_PATH": str(resolved_review_repo_path),
            "DOTMAN_REVIEW_LIVE_PATH": str(resolved_review_live_path),
            "DOTMAN_REPO_PATH": str(editable_sources[0].editable_copy_path),
            "DOTMAN_SOURCE": str(editable_sources[0].editable_copy_path),
            "DOTMAN_LIVE_PATH": str(resolved_review_live_path),
        })
        # Editors receive only editable sources positionally. The review is
        # intentionally discoverable through DOTMAN_EDITOR_REVIEW_PATH so a
        # provider cannot accidentally treat the read-only review as writable.
        positional_paths = [
            *(str(editable_source.editable_copy_path) for editable_source in editable_sources),
        ]
        if "$" in editor_value:
            command = ShellCommand(
                editor_value + " " + " ".join(shlex.quote(path) for path in positional_paths)
            )
        else:
            command = ArgvCommand((*editor_command, *positional_paths))
        result = current_command_runtime().run(
            CommandRequest(
                command=command,
                env=command_env,
                cwd=editor_cwd,
                io=editor_io,
                stream_output=stream_output if editor_io == "pipe" else False,
                elevation=editor_elevation,
            )
        )
        if result.exit_code != 0:
            return result if return_result else result.exit_code

        changed_sources = _changed_editable_sources(editable_sources)
        if not changed_sources:
            print("No reconciled repo source changes.")
            return result if return_result else 0
        if not _confirm_reconcile_write(changed_sources=changed_sources, assume_yes=assume_yes):
            return result if return_result else 0
        _write_confirmed_sources(changed_sources)
        return result if return_result else 0
