from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import dotman.reconcile as reconcile_module
from dotman.reconcile import _reconcile_write_confirmation_prompt, run_basic_reconcile


def test_reconcile_write_confirmation_prompt_uses_bracket_style() -> None:
    assert _reconcile_write_confirmation_prompt() == "Write these changes? [y/N] "


def test_run_basic_reconcile_pins_vim_like_editor_to_review_header(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        recorded["editable_text"] = Path(command[2]).read_text(encoding="utf-8")
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[],
        editor="nvim",
    )

    assert exit_code == 0
    assert recorded["command"][0] == "nvim"
    assert Path(recorded["command"][1]).name == "reconcile-review.md"
    editable_path = Path(recorded["command"][2])
    assert editable_path != repo_path.resolve()
    assert recorded["editable_text"] == "repo\n"


def test_run_basic_reconcile_opens_review_file_then_transactional_source_copies(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    review_repo_path = tmp_path / "review-repo-file"
    review_live_path = tmp_path / "review-live-file"
    include_path = tmp_path / "include-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")
    review_repo_path.write_text("rendered repo\n", encoding="utf-8")
    review_live_path.write_text("rendered live\n", encoding="utf-8")
    include_path.write_text("include\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        review_path = Path(command[1])
        editable_repo_path = Path(command[2])
        editable_include_path = Path(command[3])
        assert review_path.name == "reconcile-review.md"
        assert review_path.stat().st_mode & 0o222 == 0
        assert editable_repo_path.read_text(encoding="utf-8") == "repo\n"
        assert editable_include_path.read_text(encoding="utf-8") == "include\n"
        assert review_path.read_text(encoding="utf-8") == "\n".join(
            [
                "# Dotman Reconcile Review",
                "",
                "Review only. Do not edit this file.",
                "Inspect the diff below, then edit the temporary source copies listed under editable sources.",
                "Nothing is written back to the repo until dotman asks for confirmation after the editor exits.",
                "",
                "## Review Inputs",
                "",
                f"- review repo path: {review_repo_path.resolve()}",
                f"- review live path: {review_live_path.resolve()}",
                "",
                "## Editable Sources",
                "",
                f"- repo destination: {repo_path.resolve()}",
                f"  editable copy: {editable_repo_path}",
                f"- repo destination: {include_path.resolve()}",
                f"  editable copy: {editable_include_path}",
                "",
                "## Diff",
                "",
                "```diff",
                f"--- {review_repo_path.resolve()}",
                f"+++ {review_live_path.resolve()}",
                "@@ -1 +1 @@",
                "-rendered repo",
                "+rendered live",
                "```",
                "",
            ]
        )
        editable_repo_path.write_text("edited repo\n", encoding="utf-8")
        editable_include_path.write_text("edited include\n", encoding="utf-8")
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)
    monkeypatch.setattr(reconcile_module, "prompt", lambda _message: "y")

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[str(include_path)],
        review_repo_path=str(review_repo_path),
        review_live_path=str(review_live_path),
        editor="nvim -d",
    )

    assert exit_code == 0
    assert recorded["check"] is False
    command = recorded["command"]
    assert command[0] == "nvim"
    assert Path(command[2]) != repo_path.resolve()
    assert Path(command[3]) != include_path.resolve()
    assert repo_path.read_text(encoding="utf-8") == "edited repo\n"
    assert include_path.read_text(encoding="utf-8") == "edited include\n"


def test_run_basic_reconcile_builds_review_file_from_provided_review_paths(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    review_repo_path = tmp_path / "review-repo-file"
    review_live_path = tmp_path / "review-live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")
    review_repo_path.write_text("projected repo\n", encoding="utf-8")
    review_live_path.write_text("projected live\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        review_path = Path(command[1])
        editable_repo_path = Path(command[2])
        assert review_path.name == "reconcile-review.md"
        assert review_path.read_text(encoding="utf-8") == "\n".join(
            [
                "# Dotman Reconcile Review",
                "",
                "Review only. Do not edit this file.",
                "Inspect the diff below, then edit the temporary source copies listed under editable sources.",
                "Nothing is written back to the repo until dotman asks for confirmation after the editor exits.",
                "",
                "## Review Inputs",
                "",
                f"- review repo path: {review_repo_path.resolve()}",
                f"- review live path: {review_live_path.resolve()}",
                "",
                "## Editable Sources",
                "",
                f"- repo destination: {repo_path.resolve()}",
                f"  editable copy: {editable_repo_path}",
                "",
                "## Diff",
                "",
                "```diff",
                f"--- {review_repo_path.resolve()}",
                f"+++ {review_live_path.resolve()}",
                "@@ -1 +1 @@",
                "-projected repo",
                "+projected live",
                "```",
                "",
            ]
        )
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[],
        review_repo_path=str(review_repo_path),
        review_live_path=str(review_live_path),
        editor="nvim",
    )

    assert exit_code == 0
    assert recorded["command"][0] == "nvim"
    assert Path(recorded["command"][2]) != repo_path.resolve()


def test_run_basic_reconcile_reports_no_changes_when_editor_makes_no_edits(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")

    monkeypatch.setattr(
        "dotman.reconcile.subprocess.run",
        lambda command, check: SimpleNamespace(returncode=0),
    )
    monkeypatch.setattr(
        reconcile_module,
        "prompt",
        lambda _message: (_ for _ in ()).throw(AssertionError("prompt should not run when nothing changed")),
    )

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[],
        editor="nvim",
    )

    assert exit_code == 0
    output = capsys.readouterr().out
    assert "No reconciled repo source changes." in output



def test_run_basic_reconcile_accepts_assume_yes_without_prompting(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")

    def fake_run(command: list[str], check: bool):
        Path(command[2]).write_text("edited repo\n", encoding="utf-8")
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)
    monkeypatch.setattr(
        reconcile_module,
        "prompt",
        lambda _message: (_ for _ in ()).throw(AssertionError("prompt should not run when assume_yes is set")),
    )

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[],
        editor="nvim",
        assume_yes=True,
    )

    assert exit_code == 0
    assert repo_path.read_text(encoding="utf-8") == "edited repo\n"


def test_run_basic_reconcile_lists_only_changed_repo_sources_before_prompt(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    include_path = tmp_path / "include-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")
    include_path.write_text("include\n", encoding="utf-8")

    def fake_run(command: list[str], check: bool):
        Path(command[2]).write_text("edited repo\n", encoding="utf-8")
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)
    monkeypatch.setattr(reconcile_module, "prompt", lambda _message: "")

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[str(include_path)],
        editor="nvim",
    )

    assert exit_code == 0
    output = capsys.readouterr().out
    assert "Reconciled repo source changes:" in output
    assert f"  - {repo_path.resolve()}" in output
    assert str(include_path.resolve()) not in output



def test_run_basic_reconcile_discards_temp_edits_when_write_is_not_confirmed(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")

    def fake_run(command: list[str], check: bool):
        Path(command[2]).write_text("edited repo\n", encoding="utf-8")
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)
    monkeypatch.setattr(reconcile_module, "prompt", lambda _message: "")

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[],
        editor="nvim",
    )

    assert exit_code == 0
    assert repo_path.read_text(encoding="utf-8") == "repo\n"
