from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

from dotman.reconcile import run_basic_reconcile


def test_run_basic_reconcile_pins_vim_like_editor_to_review_header(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[],
        editor="nvim",
    )

    assert exit_code == 0
    assert recorded["command"][0] == "nvim"
    assert Path(recorded["command"][1]).name == "reconcile-review.md"
    assert recorded["command"][2] == str(repo_path.resolve())


def test_run_basic_reconcile_opens_review_file_then_editable_sources(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    review_repo_path = tmp_path / "review-repo-file"
    review_live_path = tmp_path / "review-live-file"
    include_path = tmp_path / "include-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")
    review_repo_path.write_text("rendered repo\n", encoding="utf-8")
    review_live_path.write_text("rendered live\n", encoding="utf-8")
    include_path.write_text("include\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        review_path = Path(command[1])
        assert review_path.name == "reconcile-review.md"
        assert review_path.stat().st_mode & 0o222 == 0
        assert review_path.read_text(encoding="utf-8") == "\n".join(
            [
                "# Dotman Reconcile Review",
                "",
                "Review only. Do not edit this file.",
                "Inspect the diff below, then edit the real repo source files listed under editable sources.",
                "",
                "## Review Inputs",
                "",
                f"- review repo path: {review_repo_path.resolve()}",
                f"- review live path: {review_live_path.resolve()}",
                "",
                "## Editable Sources",
                "",
                f"- {repo_path.resolve()}",
                f"- {include_path.resolve()}",
                "",
                "## Diff",
                "",
                "```diff",
                f"--- {review_repo_path.resolve()}",
                f"+++ {review_live_path.resolve()}",
                "@@ -1 +1 @@",
                "-rendered repo",
                "+rendered live",
                "```",
                "",
            ]
        )
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[str(include_path)],
        review_repo_path=str(review_repo_path),
        review_live_path=str(review_live_path),
        editor="nvim -d",
    )

    assert exit_code == 0
    assert recorded["check"] is False
    command = recorded["command"]
    assert command[0] == "nvim"
    assert command[2:] == [
        str(repo_path.resolve()),
        str(include_path.resolve()),
    ]


def test_run_basic_reconcile_builds_review_file_from_provided_review_paths(
    tmp_path: Path,
    monkeypatch,
) -> None:
    repo_path = tmp_path / "repo-file"
    live_path = tmp_path / "live-file"
    review_repo_path = tmp_path / "review-repo-file"
    review_live_path = tmp_path / "review-live-file"
    repo_path.write_text("repo\n", encoding="utf-8")
    live_path.write_text("live\n", encoding="utf-8")
    review_repo_path.write_text("projected repo\n", encoding="utf-8")
    review_live_path.write_text("projected live\n", encoding="utf-8")

    recorded: dict[str, object] = {}

    def fake_run(command: list[str], check: bool):
        recorded["command"] = command
        recorded["check"] = check
        review_path = Path(command[1])
        assert review_path.name == "reconcile-review.md"
        assert review_path.read_text(encoding="utf-8") == "\n".join(
            [
                "# Dotman Reconcile Review",
                "",
                "Review only. Do not edit this file.",
                "Inspect the diff below, then edit the real repo source files listed under editable sources.",
                "",
                "## Review Inputs",
                "",
                f"- review repo path: {review_repo_path.resolve()}",
                f"- review live path: {review_live_path.resolve()}",
                "",
                "## Editable Sources",
                "",
                f"- {repo_path.resolve()}",
                "",
                "## Diff",
                "",
                "```diff",
                f"--- {review_repo_path.resolve()}",
                f"+++ {review_live_path.resolve()}",
                "@@ -1 +1 @@",
                "-projected repo",
                "+projected live",
                "```",
                "",
            ]
        )
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("dotman.reconcile.subprocess.run", fake_run)

    exit_code = run_basic_reconcile(
        repo_path=str(repo_path),
        live_path=str(live_path),
        additional_sources=[],
        review_repo_path=str(review_repo_path),
        review_live_path=str(review_live_path),
        editor="nvim",
    )

    assert exit_code == 0
    assert recorded["command"][0] == "nvim"
    assert recorded["command"][2] == str(repo_path.resolve())
